backend:
  name: test-repo
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "artworks"
    label: "Artworks"
    folder: "src/content/artworks"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Category", name: "category", widget: "string" }
